version: '3.8'
services:
  moodle:
    image: bitnami/moodle:4.3-debian-12
    ports:
      - '8080:8080'
    environment:
      - MOODLE_USERNAME=otmane
      - MOODLE_PASSWORD=otmane
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
    volumes:
      - 'moodle_data:/bitnami/moodle'
    depends_on:
      - mariadb
    networks:
      - moodle-network

  mariadb:
    image: 'bitnami/mariadb:10.6'
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle-network

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

networks:
  moodle-network:
    driver: bridge
